import { RoutesService, eLayoutType } from '@abp/ng.core';
import { inject, provideAppInitializer } from '@angular/core';

export const APP_ROUTE_PROVIDER = [
  provideAppInitializer(() => {
    configureRoutes();
  }),
];

function configureRoutes() {
  const routes = inject(RoutesService);
  routes.add([

    // ── Home ─────────────────────────────────────────────────────────────────
    {
      path: '/',
      name: '::Menu:Home',
      iconClass: 'fas fa-home',
      order: 1,
      layout: eLayoutType.application,
    },

    // ── Companies ────────────────────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:Companies',
      iconClass: 'fas fa-building',
      order: 2,
      layout: eLayoutType.application,
    },
    {
      path: '/companies',
      name: '::Menu:Company',
      parentName: '::Menu:Companies',
      iconClass: 'fas fa-building',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Company',
    },

    // ── Site Settings ────────────────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:SiteSettings',
      iconClass: 'fas fa-sliders-h',
      order: 3,
      layout: eLayoutType.application,
    },
    {
      path: '/admin-site-settings',
      name: '::Menu:AdminSiteSetting',
      parentName: '::Menu:SiteSettings',
      iconClass: 'fas fa-sliders-h',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:AdminSiteSetting',
    },
    {
      path: '/user-site-settings',
      name: '::Menu:UserSiteSetting',
      parentName: '::Menu:SiteSettings',
      iconClass: 'fas fa-paint-brush',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:UserSiteSetting',
    },

    // ── Project Planning & Execution ─────────────────────────────────────────
    {
      path: '',
      name: '::Menu:ProjectPlanning',
      iconClass: 'fas fa-tasks',
      order: 4,
      layout: eLayoutType.application,
    },
    {
      path: '/projects',
      name: '::Menu:Projects',
      parentName: '::Menu:ProjectPlanning',
      iconClass: 'fas fa-project-diagram',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Projects',
    },
    {
      path: '/phases-timelines',
      name: '::Menu:PhasesTimelines',
      parentName: '::Menu:ProjectPlanning',
      iconClass: 'fas fa-timeline',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:PhasesTimelines',
    },
    {
      path: '/milestones-goals',
      name: '::Menu:MilestonesGoals',
      parentName: '::Menu:ProjectPlanning',
      iconClass: 'fas fa-flag-checkered',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:MilestonesGoals',
    },
    {
      path: '/team-assignment',
      name: '::Menu:TeamAssignment',
      parentName: '::Menu:ProjectPlanning',
      iconClass: 'fas fa-user-tie',
      order: 4,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:TeamAssignment',
    },
    {
      path: '/resource-allocation',
      name: '::Menu:ResourceAllocation',
      parentName: '::Menu:ProjectPlanning',
      iconClass: 'fas fa-cubes',
      order: 5,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:ResourceAllocation',
    },

    // ── Asset & Site Management ──────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:AssetSiteManagement',
      iconClass: 'fas fa-solar-panel',
      order: 5,
      layout: eLayoutType.application,
    },
    {
      path: '/sites',
      name: '::Menu:Sites',
      parentName: '::Menu:AssetSiteManagement',
      iconClass: 'fas fa-map-location-dot',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Sites',
    },
    {
      path: '/assets',
      name: '::Menu:Assets',
      parentName: '::Menu:AssetSiteManagement',
      iconClass: 'fas fa-microchip',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Assets',
    },
    {
      path: '/preventive-maintenance',
      name: '::Menu:PreventiveMaintenance',
      parentName: '::Menu:AssetSiteManagement',
      iconClass: 'fas fa-calendar-check',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:PreventiveMaintenance',
    },
    {
      path: '/asset-performance',
      name: '::Menu:AssetPerformance',
      parentName: '::Menu:AssetSiteManagement',
      iconClass: 'fas fa-chart-area',
      order: 4,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:AssetPerformance',
    },

    // ── Site Inspections & Subcontracts ──────────────────────────────────────
    {
      path: '',
      name: '::Menu:SiteInspections',
      iconClass: 'fas fa-search',
      order: 6,
      layout: eLayoutType.application,
    },
    {
      path: '/inspections',
      name: '::Menu:Inspections',
      parentName: '::Menu:SiteInspections',
      iconClass: 'fas fa-clipboard-check',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Inspections',
    },
    {
      path: '/inspection-teams',
      name: '::Menu:InspectionTeams',
      parentName: '::Menu:SiteInspections',
      iconClass: 'fas fa-users-medical',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:InspectionTeams',
    },
    {
      path: '/subcontracts',
      name: '::Menu:Subcontracts',
      parentName: '::Menu:SiteInspections',
      iconClass: 'fas fa-file-contract',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Subcontracts',
    },

    // ── Inventory & Procurement ──────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:InventoryProcurement',
      iconClass: 'fas fa-boxes',
      order: 7,
      layout: eLayoutType.application,
    },
    {
      path: '/products',
      name: '::Menu:Product',
      parentName: '::Menu:InventoryProcurement',
      iconClass: 'fas fa-tag',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Product',
    },
    {
      path: '/stock-entries',
      name: '::Menu:StockEntry',
      parentName: '::Menu:InventoryProcurement',
      iconClass: 'fas fa-warehouse',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:StockEntry',
    },
    {
      path: '/stock-ledger',
      name: '::Menu:StockLedger',
      parentName: '::Menu:InventoryProcurement',
      iconClass: 'fas fa-clipboard-list',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:StockLedger',
    },
    {
      path: '/suppliers',
      name: '::Menu:Suppliers',
      parentName: '::Menu:InventoryProcurement',
      iconClass: 'fas fa-truck',
      order: 4,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Suppliers',
    },
    {
      path: '/purchase-orders',
      name: '::Menu:PurchaseOrders',
      parentName: '::Menu:InventoryProcurement',
      iconClass: 'fas fa-list-check',
      order: 5,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:PurchaseOrders',
    },
    {
      path: '/quotes-deliveries',
      name: '::Menu:QuotesDeliveries',
      parentName: '::Menu:InventoryProcurement',
      iconClass: 'fas fa-cube',
      order: 6,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:QuotesDeliveries',
    },

    // ── Workforce & Task Management ──────────────────────────────────────────
    {
      path: '',
      name: '::Menu:WorkforceTaskManagement',
      iconClass: 'fas fa-hard-hat',
      order: 8,
      layout: eLayoutType.application,
    },
    {
      path: '/technicians',
      name: '::Menu:Technicians',
      parentName: '::Menu:WorkforceTaskManagement',
      iconClass: 'fas fa-user-astronaut',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Technicians',
    },
    {
      path: '/tasks',
      name: '::Menu:Tasks',
      parentName: '::Menu:WorkforceTaskManagement',
      iconClass: 'fas fa-checklist',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Tasks',
    },
    {
      path: '/attendance',
      name: '::Menu:Attendance',
      parentName: '::Menu:WorkforceTaskManagement',
      iconClass: 'fas fa-user-check',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Attendance',
    },
    {
      path: '/shift-scheduling',
      name: '::Menu:ShiftScheduling',
      parentName: '::Menu:WorkforceTaskManagement',
      iconClass: 'fas fa-calendar-days',
      order: 4,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:ShiftScheduling',
    },
    {
      path: '/payroll',
      name: '::Menu:Payroll',
      parentName: '::Menu:WorkforceTaskManagement',
      iconClass: 'fas fa-money-bill-wave',
      order: 5,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Payroll',
    },

    // ── Maintenance & Service Management ─────────────────────────────────────
    {
      path: '',
      name: '::Menu:MaintenanceService',
      iconClass: 'fas fa-wrench',
      order: 9,
      layout: eLayoutType.application,
    },
    {
      path: '/work-orders',
      name: '::Menu:WorkOrders',
      parentName: '::Menu:MaintenanceService',
      iconClass: 'fas fa-hammer',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:WorkOrders',
    },
    {
      path: '/maintenance-plans',
      name: '::Menu:MaintenancePlans',
      parentName: '::Menu:MaintenanceService',
      iconClass: 'fas fa-sitemap',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:MaintenancePlans',
    },
    {
      path: '/repair-history',
      name: '::Menu:RepairHistory',
      parentName: '::Menu:MaintenanceService',
      iconClass: 'fas fa-history',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:RepairHistory',
    },
    {
      path: '/service-costs',
      name: '::Menu:ServiceCosts',
      parentName: '::Menu:MaintenanceService',
      iconClass: 'fas fa-receipt',
      order: 4,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:ServiceCosts',
    },

    // ── Sales ────────────────────────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:Sales',
      iconClass: 'fas fa-shopping-cart',
      order: 10,
      layout: eLayoutType.application,
    },
    {
      path: '/point-of-sales',
      name: '::Menu:PointOfSales',
      parentName: '::Menu:Sales',
      iconClass: 'fas fa-cash-register',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:PointOfSales',
    },
    {
      path: '/pos-counters',
      name: '::Menu:POSCounters',
      parentName: '::Menu:Sales',
      iconClass: 'fas fa-desktop',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:POSCounters',
    },
    {
      path: '/sales-invoices',
      name: '::Menu:SalesInvoice',
      parentName: '::Menu:Sales',
      iconClass: 'fas fa-file-invoice-dollar',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:SalesInvoice',
    },
    {
      path: '/product-returns',
      name: '::Menu:ProductReturn',
      parentName: '::Menu:Sales',
      iconClass: 'fas fa-undo-alt',
      order: 4,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:ProductReturn',
    },
    {
      path: '/promotions',
      name: '::Menu:Promotion',
      parentName: '::Menu:Sales',
      iconClass: 'fas fa-percentage',
      order: 5,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Promotion',
    },
    {
      path: '/customers',
      name: '::Menu:Customer',
      parentName: '::Menu:Sales',
      iconClass: 'fas fa-users',
      order: 6,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Customer',
    },
    {
      path: '/catalogues',
      name: '::Menu:Catalogue',
      parentName: '::Menu:Sales',
      iconClass: 'fas fa-layer-group',
      order: 7,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Catalogue',
    },

    // ── E-Commerce ───────────────────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:ECommerce',
      iconClass: 'fas fa-shopping-bag',
      order: 11,
      layout: eLayoutType.application,
    },
    {
      path: '/orders',
      name: '::Menu:Orders',
      parentName: '::Menu:ECommerce',
      iconClass: 'fas fa-receipt',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Orders',
    },

    // ── Shipping & Courier Setup ─────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:ShippingCourier',
      iconClass: 'fas fa-truck-fast',
      order: 12,
      layout: eLayoutType.application,
    },
    {
      path: '/shipping-setup',
      name: '::Menu:ShippingSetup',
      parentName: '::Menu:ShippingCourier',
      iconClass: 'fas fa-shipping-fast',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:ShippingSetup',
    },

    // ── Financials & Billing ─────────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:FinancialsBilling',
      iconClass: 'fas fa-chart-pie',
      order: 13,
      layout: eLayoutType.application,
    },
    {
      path: '/budgets-costs',
      name: '::Menu:BudgetsCosts',
      parentName: '::Menu:FinancialsBilling',
      iconClass: 'fas fa-coins',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:BudgetsCosts',
    },
    {
      path: '/service-invoices',
      name: '::Menu:ServiceInvoices',
      parentName: '::Menu:FinancialsBilling',
      iconClass: 'fas fa-file-invoice',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:ServiceInvoices',
    },
    {
      path: '/funding-sources',
      name: '::Menu:FundingSources',
      parentName: '::Menu:FinancialsBilling',
      iconClass: 'fas fa-piggy-bank',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:FundingSources',
    },

    // ── Compliance & Documentation ───────────────────────────────────────────
    {
      path: '',
      name: '::Menu:ComplianceDocumentation',
      iconClass: 'fas fa-certificate',
      order: 14,
      layout: eLayoutType.application,
    },
    {
      path: '/audits-inspections',
      name: '::Menu:AuditsInspections',
      parentName: '::Menu:ComplianceDocumentation',
      iconClass: 'fas fa-magnifying-glass',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:AuditsInspections',
    },
    {
      path: '/compliance-documents',
      name: '::Menu:ComplianceDocuments',
      parentName: '::Menu:ComplianceDocumentation',
      iconClass: 'fas fa-file-pdf',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:ComplianceDocuments',
    },
    {
      path: '/safety-regulations',
      name: '::Menu:SafetyRegulations',
      parentName: '::Menu:ComplianceDocumentation',
      iconClass: 'fas fa-shield',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:SafetyRegulations',
    },

    // ── Analytics & Reporting ────────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:AnalyticsReporting',
      iconClass: 'fas fa-chart-bar',
      order: 15,
      layout: eLayoutType.application,
    },
    {
      path: '/dashboard',
      name: '::Menu:Dashboard',
      parentName: '::Menu:AnalyticsReporting',
      iconClass: 'fas fa-gauge',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Dashboard',
    },
    {
      path: '/reports',
      name: '::Menu:Reports',
      parentName: '::Menu:AnalyticsReporting',
      iconClass: 'fas fa-scroll',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Reports',
    },
    {
      path: '/charts-views',
      name: '::Menu:ChartsViews',
      parentName: '::Menu:AnalyticsReporting',
      iconClass: 'fas fa-chart-line',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:ChartsViews',
    },

    // ── Marketing ────────────────────────────────────────────────────────────
    {
      path: '',
      name: '::Menu:Marketing',
      iconClass: 'fas fa-megaphone',
      order: 16,
      layout: eLayoutType.application,
    },
    {
      path: '/marketing-overview',
      name: '::Menu:MarketingOverview',
      parentName: '::Menu:Marketing',
      iconClass: 'fas fa-bullhorn',
      order: 1,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:MarketingOverview',
    },
    {
      path: '/integrations',
      name: '::Menu:Integrations',
      parentName: '::Menu:Marketing',
      iconClass: 'fas fa-link',
      order: 2,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:Integrations',
    },
    {
      path: '/sms-campaigns',
      name: '::Menu:SMSCampaigns',
      parentName: '::Menu:Marketing',
      iconClass: 'fas fa-sms',
      order: 3,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:SMSCampaigns',
    },
    {
      path: '/email-campaigns',
      name: '::Menu:EmailCampaigns',
      parentName: '::Menu:Marketing',
      iconClass: 'fas fa-envelope',
      order: 4,
      layout: eLayoutType.application,
      breadcrumbText: '::Menu:EmailCampaigns',
    },

  ]);
}
